title: Tipsy Typography
description: Typography for alcohol fanatics
header_text: ""
footer_text: Copyright 2020 Abby Shaw
header_feature_image: ../uploads/tipsytypographybanner.png
bannerheight: 20vmax
logo: ../uploads/your-paragraph-text.png
favicon: ../uploads/your-paragraph-text.png
gridlayout: false
fixednavbar: false
upzoom: true
