title: Tipsy Typography
description: A website with a blog
header_text: Tipsy Typography
footer_text: Copyright 2020 Abby Shaw
header_feature_image: ../uploads/your-paragraph-text.jpg
bannerheight: 20vmax
logo: ../uploads/your-paragraph-text.png
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
