title: Tipsy Typography
description: Typography for alcohol fanatics
header_text: ""
footer_text: Copyright 2020 Abby Shaw
header_feature_image: ../uploads/ttbanner1.png
bannerheight: 20vmax
logo: ../uploads/ttlogofinal2.png
favicon: ../uploads/ttlogo3.png
gridlayout: false
fixednavbar: false
upzoom: true
